
import React from 'react';
import { Language } from './types';

export const APP_NAME = "መራሔ ጥበብ";

export const APP_ICON = "https://i.ibb.co/689V8X3/app-icon.jpg";
export const CHURCH_HEADER_IMG = "https://i.ibb.co/9VzR6mR/orthodox-banner.jpg";
export const RELIGIOUS_BANNER = "https://images.unsplash.com/photo-1544013508-222218bcc383?q=80&w=1200";

export const LANGUAGES: { id: Language; label: string }[] = [
  { id: 'Amharic', label: 'አማርኛ' },
  { id: 'Geez', label: 'ግዕዝ' },
  { id: 'Tigrinya', label: 'ትግርኛ' },
  { id: 'English', label: 'English' },
  { id: 'AfaanOromo', label: 'Afaan Oromo' }
];

export const TRANSLATIONS: Record<Language, any> = {
  Amharic: {
    home: 'መነሻ',
    audio: 'ኦዲዮ',
    bible: 'ፈልግ',
    community: 'ማህበር',
    settings: 'ቅንብር',
    categories: 'ዝርዝሮች',
    changeLanguage: 'ቋንቋ ቀይር',
    monasteries: 'ገዳማት',
    abnet: 'የአብነት ትምህርት',
    teachers: 'ዐበይት መምህራን',
    holidays: 'በዓላት',
    search: 'ፈልግ',
    prayerRequest: 'የጸሎት ጥያቄ',
    submit: 'ላክ',
    loading: 'በመዘጋጀት ላይ...',
    noResults: 'ምንም አልተገኘም',
    textSize: 'የታሪክ ጽሁፍ መጠን',
    preview: 'የጽሁፍ ቅድመ እይታ',
    historyPreview: 'ይህ የታሪክ ጽሁፎች በዚህ መጠን እንደሚታዩ የሚያሳይ ናሙና ነው። የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተክርስቲያን ረጅም ታሪክ ያላት ጥንታዊት ቤተክርስቲያን ናት።',
    darkMode: 'Dark Mode',
    aboutUs: 'ስለ እኛ',
    rateUs: 'ደረጃ ይስጡ',
    aboutTitle: "መራሔ ጥበብ",
    aboutSubtitle: "የታሪክ ረዳትዎ",
    aboutWelcome: "እንኳን ወደ መራሔ ጥበብ በደህና መጡ - የታሪክ ረዳትዎ",
    aboutBody: "መራሔ ጥበብ የቤተክርስቲያን መንፈሳዊና ታሪካዊ ቅርስን ለማስጠበቅ እና ለማስተላለፍ የተፈጠረ ዲጂታል መተግበሪያ ነው። መተግበሪያው የገዳማት ታሪክ፣ የቤተክርስቲያን ትምህርት፣ የታላላቅ መምህራን ሕይወትና ትምህርት እንዲሁም የቅዱሳን በዓላትን መንፈሳዊ ትርጉም ያቀርባል። ባህላዊ እውቀትን ከዘመናዊ ቴክኖሎጂ ጋር በማጣመር፣ መራሔ ጥበብ ለተማሪዎች፣ ለምሁራን እና ለማንኛውም የእምነት ፍላጎት ያለው ሰው ተደራሽ የሆነ መድረክ ይሆናል።",
    aboutUnderline: "\"ታሪኩን የማያውቅ ትውልድ ስር እንደሌለው ዛፍ ነው!\" መራሔ ጥበብ ለዚህ የዲጂታል ዘመን ይሄንን ስር እየገነባ መሆኑ በግልጽ ይታያል::",
    getInTouch: "ያግኙን",
    emailUs: "ኢሜይል ያድርጉልን",
    ask: 'ጠይቅ',
    pray: 'ጸልይ',
    name: 'ስም',
    request: 'ጥያቄ',
    newest: 'አዲስ',
    oldest: 'የቆየ',
    readingReminder: 'የንባብ ማስታወሻ',
    setTime: 'ሰዓት ይምረጡ',
    notificationAndReminder: 'ማሳሰቢያ እና ማስታወሻ'
  },
  Geez: {
    home: 'መነሻ',
    audio: 'ኦዲዮ',
    bible: 'ኅሥሥ',
    community: 'ማህበር',
    settings: 'ቅንብር',
    categories: 'ዝርዝሮች',
    changeLanguage: 'ቋንቋ ቀይር',
    monasteries: 'ገዳማት',
    abnet: 'ትምህርተ አብነት',
    teachers: 'መምህራን',
    holidays: 'በዓላት',
    search: 'ኅሥሥ',
    prayerRequest: 'ስእለት',
    submit: 'ፈኑ',
    loading: 'ናሁ...',
    noResults: 'አልተረክበ',
    textSize: 'መጠነ ፊደላት',
    preview: 'ቅድመ እይታ',
    historyPreview: 'ዝንቱ ውእቱ ጽሑፍ ዘይሬኢ መጠነ ፊደላት። ኢትዮጵያ ሀገረ እግዚአብሔር ይእቲ።',
    darkMode: 'Dark Mode',
    aboutUs: 'በእንተ አፕ',
    rateUs: 'Rate Us',
    aboutTitle: "መራሔ ጥበብ",
    aboutSubtitle: "መስተዓግሥ ታሪክ",
    aboutWelcome: "ሰላም ለክሙ ኀበ መራሔ ጥበብ - መስተዓግሥ ታሪክክሙ",
    aboutBody: "መራሔ ጥበብ ውእቱ መርበብ ዘዲጂታል ዘተፈጥረ ለዐቅቦተ ታሪክ ወመንፈሳዊ ሀብተ ቤተ ክርስቲያን። ዝንቱ መተግበሪያ ያቀርብ ታሪከ ገዳማት፣ ትምህርተ አብነት፣ ዜና መዋዕል ዘመምህራን ወትርጓሜ በዓላት።",
    aboutUnderline: "\"ትውልድ ዘኢየአምር ታሪኮ ይመስል ዕፀ ዘአልቦ ሥርወ!\" መራሔ ጥበብ ውእቱ ዘይተክል ሥርወ ለዝንቱ ትውልደ ዲጂታል::",
    getInTouch: "ያግኙን",
    emailUs: "ኢሜይል",
    ask: 'ሰአል',
    pray: 'ጸሊ',
    name: 'ስም',
    request: 'ስእለት',
    newest: 'ሐዲስ',
    oldest: 'ብሉይ',
    readingReminder: 'ዝክረ ንባብ',
    setTime: 'ጊዜ ይኅረዩ'
  },
  English: {
    home: 'Home',
    audio: 'Audio',
    bible: 'Search',
    community: 'Community',
    settings: 'Settings',
    categories: 'Categories',
    changeLanguage: 'Language',
    monasteries: 'Monasteries',
    abnet: 'Church Education',
    teachers: 'Great Teachers',
    holidays: 'Holidays',
    search: 'Search',
    prayerRequest: 'Prayer',
    submit: 'Submit',
    loading: 'Loading...',
    noResults: 'No results',
    textSize: 'Change History Text Size',
    preview: 'Text Preview',
    historyPreview: 'This is a sample of how the history text will look at this size. The Ethiopian Orthodox Tewahedo Church has a very rich and ancient history.',
    darkMode: 'Dark Mode',
    aboutUs: 'About Us',
    rateUs: 'Rate Us',
    aboutTitle: "Merahe Tibeb",
    aboutSubtitle: "your history Companion",
    aboutWelcome: "Welcome to Merahe Tibeb - your history Companion",
    aboutBody: "Merahe Tibeb is a knowledge-centred digital platform created to preserve, explore, and share the spiritual, educational, and historical heritage of the Church. My app brings together the history of monasteries, the tradition of church education, the legacy of eminent teachers, and the meaning of religious holidays in one accessible space. Monasteries have long been the heart of faith, learning, and cultural preservation. Through Merahe Tibeb, users can discover the origins, roles, and historical journeys of these sacred places, along with their influence on spiritual life and scholarship. The app also highlights the depth of church education—its structure, disciplines, and transmission of wisdom across generations. We honor eminent teachers whose lives, teachings, and contributions have shaped faith, knowledge, and moral guidance throughout history. In addition, Merahe Tibeb presents religious holidays and commemorations, explaining their spiritual meaning, historical background, and significance in the life of the Church and its followers. Our mission is to safeguard this priceless heritage and make it accessible to learners, believers, and researchers in the modern digital age. Merahe Tibeb stands as a bridge between tradition and technology—preserving the past, educating the present, and inspiring the future.",
    aboutUnderline: "\"A generation that does not know its history is like a tree without roots.\" Merahe Tibeb is clearly providing those roots for the digital generation.",
    getInTouch: "Get in Touch",
    emailUs: "Email Us",
    ask: 'Ask',
    pray: 'Pray',
    name: 'Name',
    request: 'Request',
    newest: 'Newest',
    oldest: 'Oldest',
    readingReminder: 'Reading Reminder',
    setTime: 'Set Time',
    notificationAndReminder: 'Notification and Reminder'
  },
  Tigrinya: {
    home: 'መበገሲ',
    audio: 'ኦዲዮ',
    bible: 'ድለ',
    community: 'ማሕበር',
    settings: 'ቅንብራት',
    categories: 'ዝርዝራት',
    changeLanguage: 'ቋንቋ',
    monasteries: 'ገዳማት',
    abnet: 'ትምህርቲ አብነት',
    teachers: 'መምህራን',
    holidays: 'በዓላት',
    search: 'ድለ',
    prayerRequest: 'ሕቶ ጸሎት',
    submit: 'ሰድድ',
    loading: 'ይዳለወ ኣሎ...',
    noResults: 'ኣይተረኸበን',
    textSize: 'ዓቀን ጽሑፍ',
    preview: 'ቅድመ ምርኢት',
    historyPreview: 'እዚ ጽሑፍ እዚ ዓቀን ፊደላት ከመይ ከምዝኸውን ዘርኢ ናሙና እዩ።',
    darkMode: 'Dark Mode',
    aboutUs: 'ብዛዕባና',
    rateUs: 'ደረጃ ሃቡ',
    aboutTitle: "መራሔ ጥበብ",
    aboutSubtitle: "መሓዛ ታሪኽኩም",
    aboutWelcome: "እንቋዕ ናብ መራሔ ጥበብ ብደሓን መጻእኩም - ናይ ታሪኽ መሓዛኹም",
    aboutBody: "መራሔ ጥበብ መንፈሳዊን ታሪኻዊን ርስቲ ቤተክርስቲያን ንምዕቃብን ንምትሕልላፍን ዝተዳለወ ዲጂታል መተግበሪ እዩ። እዚ መተግበሪ እዚ ታሪኽ ገዳማት፣ ትምህርቲ አብነት፣ ታሪኽ ህይወት መምህራንን ትርጉም በዓላትን ብሓደ ዝሓዘ እዩ።",
    aboutUnderline: "\"ታሪኹ ዘይፈልጥ ወለዶ ከምቲ ስር ዘይብሉ ኦም እዩ!\" መራሔ ጥበብ ነዚ ናይ ዲጂታል ዘመን እዚ ስር ይሰርሓሉ ከምዘሎ ብንጹር ይርአ።",
    getInTouch: "ርኸቡና",
    emailUs: "ኢሜይል",
    ask: 'ሕተ',
    pray: 'ጸሊ',
    name: 'ስም',
    request: 'ሕቶ',
    newest: 'ሓድሽ',
    oldest: 'ቀደም',
    readingReminder: 'መዘኻኸሪ ንባብ',
    setTime: 'ሰዓት ይምረጡ'
  },
  AfaanOromo: {
    home: 'Mana',
    audio: 'Audio',
    bible: 'Barባዲ',
    community: 'Hawaasa',
    settings: 'Saguu',
    categories: 'Ramaddii',
    changeLanguage: 'Qooqa',
    monasteries: 'Gadamoota',
    abnet: 'Barnoota',
    teachers: 'Barsiisota',
    holidays: 'Ayyaana',
    search: 'Barባዲ',
    prayerRequest: 'Kadhannaa',
    submit: 'Ergi',
    loading: 'Qophaayaa jira...',
    noResults: 'Hin argamne',
    textSize: 'Hamma qubee',
    preview: 'Ilaalcha',
    historyPreview: 'Barreeffamni kun hamma qubeewwan seenaa akkamitti akka mul\'atu kan agarsiisudha.',
    darkMode: 'Dark Mode',
    aboutUs: "Waa'ee Keenya",
    rateUs: 'Sadarkaa Kennaa',
    aboutTitle: "መራሔ ጥበብ",
    aboutSubtitle: "Hiriyyaa seenaa keessanii",
    aboutWelcome: "Baga nagaan gara መራሔ ጥበብ dhuftan - Hiriyyaa seenaa keessanii",
    aboutBody: "መራሔ ጥበብ appii dijitaalaa qabeenya hafuuraa fi seenaa mana kiristaanaa eeguuf qophaa'edha. Appiin kun seenaa gadamootaa, barnoota mana kiristaanaa, seenaa barsiisotaa fi hiika ayyaanotaa iddoo tokkotti walitti qaba.",
    aboutUnderline: "\"Dhalootni seenaa isaa hin beekne akka mukeetii hundee hin qabneeti!\" መራሔ ጥበብ dhaloota dijitaalaa kanaaf hundee ijaaraa jiraachuun isaa ifatti mul'ata.",
    getInTouch: "Nu Quunnamaa",
    emailUs: "Email Nuuf Ergaa",
    ask: 'Gaaffadhu',
    pray: 'Kadhadhu',
    name: 'Maqaa',
    request: 'Gaaffii',
    newest: 'Haaraa',
    oldest: 'Kan duraa',
    readingReminder: 'Yaadachiisa Dubbisaa',
    setTime: 'Sa\'aatii filadhu'
  }
};
